const taskStatusStorageKeyOverride = 'dancesport30_task_statuses';
state.taskStatuses = JSON.parse(localStorage.getItem(taskStatusStorageKeyOverride) || '{}');
function statusKey(lessonId, taskIndex) { return `${lessonId}:${taskIndex}`; }
function taskStatus(lessonId, taskIndex) { const saved=state.taskStatuses[statusKey(lessonId,taskIndex)]; if(saved)return saved; const entry=taskEntries(lessonId,taskIndex)[0]; return ['done','mastered','confident'].includes(entry?.status)?'completed':['needs-review','practiced'].includes(entry?.status)?'in-progress':'not-started'; }
function entryHasStarted(entry){const today=new Date();const todayText=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;return Boolean(entry.session_date&&entry.session_date<=todayText);}
function lessonStarted(lesson){const entries=state.entries.filter(entry=>Number(entry.lesson_id)===lesson.id);return entries.length?entries.some(entryHasStarted):lesson.tasks.some((_,index)=>taskStatus(lesson.id,index)!=='not-started');}
function overview(){
  const lessonIsCompleted=lesson=>lessonCompleted(lesson);
  const completed=lessons.filter(lessonIsCompleted).length;
  const started=lessons.filter(lessonStarted).length;
  const activitiesNotCompleted=lessons.filter(lessonStarted).reduce((total,lesson)=>total+lesson.tasks.filter((_,index)=>taskStatus(lesson.id,index)!=='completed').length,0);
  $('#progress-overview').innerHTML=`<div class="metric"><b>${started}<small>/30</small></b><span>Lessons started</span></div><div class="metric"><b>${completed}<small>/30</small></b><span>Lessons completed</span></div><div class="metric"><b>${activitiesNotCompleted}</b><span>Activities planned, not completed</span></div>`;
}
function lessonCompleted(lesson){ return lessonStarted(lesson)&&lesson.tasks.every((_,index)=>taskStatus(lesson.id,index)==='completed'); }
function entryMarkup(){ return ''; }
function displayDate(dateText){return new Date(`${dateText}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function summaryView(items){return `<div class="summary-grid">${items.map(lesson=>{const phase=phaseFor(lesson.phase),completed=lessonCompleted(lesson),started=lessonStarted(lesson),start=lessonStartEntry(lesson.id),completion=state.entries.find(entry=>Number(entry.lesson_id)===lesson.id&&['completed','done','mastered','confident'].includes(entry.status));const stateClass=completed?'completed-lesson':started?'started-incomplete-lesson':'';const status=completed?'Completed':started?'In progress':'Not started';const date=completed&&completion?.session_date?`Completed on ${displayDate(completion.session_date)}`:started&&start?.session_date?`Started on ${displayDate(start.session_date)}`:'Not started';return `<article class="summary-card ${stateClass}"><div class="summary-top"><span class="lesson-number">Lesson ${String(lesson.id).padStart(2,'0')}</span><span class="status-pill ${completed?'completed':started?'in-progress':'not-started'}">${status}</span></div><h2>${safe(detailedTitle(lesson))}</h2><p class="lesson-meta">${safe(phase.title)}</p><p class="lesson-meta">${safe(date)}</p><span class="phase-pill">${safe(phase.principle)}</span><button class="button lesson-log-button" data-lesson="${lesson.id}">Log progress</button></article>`;}).join('')}</div>`;}
function phaseView(){return `<div class="phase-grid">${phases.map(phase=>{const phaseLessons=lessons.filter(lesson=>lesson.phase===phase.id),completed=phaseLessons.filter(lessonCompleted).length,started=phaseLessons.filter(lessonStarted).length,remaining=phaseLessons.filter(lessonStarted).reduce((total,lesson)=>total+lesson.tasks.filter((_,index)=>taskStatus(lesson.id,index)!=='completed').length,0),stateClass=completed===phaseLessons.length?'completed-lesson':started?'started-incomplete-lesson':'';return `<article class="phase-card ${stateClass}"><span class="phase-number">0${phase.id}</span><div><p class="eyebrow">${safe(phase.range)}</p><h2>${safe(phase.title)}</h2><p>${safe(phase.summary)}</p><p class="lesson-meta">${completed}/${phaseLessons.length} lessons completed · ${started} started${started?` · ${remaining} activities planned, not completed`:''}</p></div><span class="principle-pill">${safe(phase.principle)}</span></article>`;}).join('')}</div>`;}
function lessonStartEntry(lessonId){ return state.entries.filter(entry=>Number(entry.lesson_id)===lessonId&&entry.session_date).sort((a,b)=>String(a.session_date).localeCompare(String(b.session_date)))[0]; }
function latestLessonEntry(lessonId){return state.entries.filter(entry=>Number(entry.lesson_id)===lessonId).sort((a,b)=>String(b.created_at||b.session_date||'').localeCompare(String(a.created_at||a.session_date||'')))[0];}
function openProgress(event){const lesson=lessons.find(item=>item.id===Number(event.currentTarget.dataset.lesson));const existing=latestLessonEntry(lesson.id);const status=['not-started','in-progress','completed'].includes(existing?.status)?existing.status:existing?.status==='done'?'completed':'not-started';$('#lesson-id').value=lesson.id;$('#task-index').value='0';$('#dialog-title').textContent=`Lesson ${String(lesson.id).padStart(2,'0')} · Log progress`;$('#session-date').value=existing?.session_date||new Date().toISOString().slice(0,10);$('#instructor').value=existing?.instructor||'Davit';$('#status').value=status;$('#notes').value=existing?.notes||'';const videos=[...(existing?.video_urls||[]),...(existing?.video_url?[existing.video_url]:[])];const videoLinks=$('#video-links');videoLinks.innerHTML='';(videos.length?videos:['']).forEach(url=>{const input=document.createElement('input');input.className='video-url';input.type='url';input.placeholder='https://… (optional)';input.value=url;videoLinks.appendChild(input);});$('#progress-dialog').showModal();}
async function updateTaskStatus(lessonId, taskIndex, status, retried = false) { state.taskStatuses[statusKey(lessonId,taskIndex)]=status; localStorage.setItem(taskStatusStorageKeyOverride,JSON.stringify(state.taskStatuses)); if(state.config&&state.session){const response=await fetch(`${state.config.url}/rest/v1/task_statuses?on_conflict=lesson_id,task_index`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates'},body:JSON.stringify({lesson_id:lessonId,task_index:taskIndex,status,updated_at:new Date().toISOString()})});if(response.status===401&&!retried&&typeof renewAnonymousSupabaseSession==='function'){await renewAnonymousSupabaseSession();return updateTaskStatus(lessonId,taskIndex,status,true);}if(!response.ok)setSync('Status saved locally · shared sync needs update');} render(); }
function detailView(items){return `<div class="lesson-list">${items.map(lesson=>{const phase=phaseFor(lesson.phase);return `<details class="lesson-card"><summary><span class="lesson-number">Lesson ${String(lesson.id).padStart(2,'0')}</span><span><h2>${safe(detailedTitle(lesson))}</h2><p class="lesson-meta">${safe(phase.title)}</p></span><span class="phase-pill">${safe(phase.principle)}</span></summary><div class="lesson-body"><div class="lesson-action-bar"><span class="lesson-total">Total allocated: <b>${totalAllocated(lesson)} min</b></span><button class="button lesson-log-button" data-lesson="${lesson.id}">Log progress</button></div><table class="task-table"><thead><tr><th>Time</th><th>Block</th><th>Frame</th><th>Style</th><th>Dance</th><th>Activity</th><th>Progress</th></tr></thead><tbody>${lesson.tasks.map((item,index)=>{const entries=taskEntries(lesson.id,index),status=taskStatus(lesson.id,index),block=displayBlock(lesson,item,index),one=lesson.id===1&&index===4,three=lesson.id===3&&index===1,phase3=isPhaseThreeClosedFigureBlock(lesson,item,index,block),figures=phase3?phaseThreeFigureNames(lesson,item,index,block):block==='Practice'&&item.type==='Closed figures'?'':item.figures,activity=phase3?'Closed figures 4–5':((lesson.id===1||lesson.id===2)&&index===1)||(block==='New'&&figures)?'Closed figures 1–3':lesson.id>=3&&lesson.id<=8&&block==='Review'?'Review closed figures 1–3':item.detail,dance=lesson.id===20&&index===4?'Mambo':one||three?'Waltz':isNonDanceActivity(item)?'NA':item.dance;return `<tr><td>${safe(item.minutes)}</td><td>${safe(block)}</td><td>${safe(one?'Open':three?'Closed':isNonDanceActivity(item)?'NA':displayFrame(item.frame))}</td><td>${safe(taskStyle(item,lesson))}</td><td>${safe(dance)}</td><td>${safe(activity)}${figures?`<br><span class="figures">${safe(figures)}</span>`:''}</td><td><select class="inline-status ${status}" data-lesson="${lesson.id}" data-task="${index}"><option value="not-started"${status==='not-started'?' selected':''}>Not Started</option><option value="in-progress"${status==='in-progress'?' selected':''}>In Progress</option><option value="completed"${status==='completed'?' selected':''}>Completed</option></select>${entryMarkup(entries)}</td></tr>`}).join('')}</tbody></table></div></details>`}).join('')}</div>`;}
function applyCompletionDates(){document.querySelectorAll('.lesson-card').forEach(card=>{const lessonId=Number(card.querySelector('.lesson-number')?.textContent.match(/\d+/)?.[0]);const lesson=lessons.find(item=>item.id===lessonId);const meta=card.querySelector('.lesson-meta');const start=lessonStartEntry(lessonId);if(lesson&&lessonStarted(lesson)&&start?.session_date){const date=new Date(`${start.session_date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});meta.textContent=`${meta.textContent} · Started on ${date}`;}const completion=state.entries.find(item=>Number(item.lesson_id)===lessonId&&['completed','done','mastered','confident'].includes(item.status));if(lesson&&lessonCompleted(lesson)&&completion?.session_date){const date=new Date(`${completion.session_date}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});meta.textContent=`${meta.textContent} · Completed on ${date}`;}});}
function applyCompletedLessonStyling(){document.querySelectorAll('.lesson-card').forEach(card=>{const lessonId=Number(card.querySelector('.lesson-number')?.textContent.match(/\d+/)?.[0]);const lesson=lessons.find(item=>item.id===lessonId);const completed=Boolean(lesson&&lessonCompleted(lesson));card.classList.toggle('completed-lesson',completed);card.classList.toggle('started-incomplete-lesson',Boolean(lesson&&lessonStarted(lesson)&&!completed));});}
function render(){const openLessons=new Set([...document.querySelectorAll('details.lesson-card[open]')].map(detail=>detail.querySelector('.lesson-number')?.textContent.match(/\d+/)?.[0]));overview();const items=filteredLessons();$('#view-root').innerHTML=items.length?(state.view==='detail'?detailView(items):state.view==='summary'?summaryView(items):phaseView()):$('#empty-template').innerHTML;applyCompletionDates();applyCompletedLessonStyling();document.querySelectorAll('details.lesson-card').forEach(detail=>{if(openLessons.has(detail.querySelector('.lesson-number')?.textContent.match(/\d+/)?.[0]))detail.open=true;});document.querySelectorAll('.lesson-log-button').forEach(button=>button.addEventListener('click',openProgress));document.querySelectorAll('.inline-status').forEach(select=>select.addEventListener('change',event=>updateTaskStatus(Number(event.target.dataset.lesson),Number(event.target.dataset.task),event.target.value)));}
render();
